CREATE SEQUENCE PM_CHANGE_REQUEST_SEQ START WITH 1 INCREMENT BY 1 CACHE 20;
CREATE SEQUENCE PM_CHANGE_ITEM_SEQ START WITH 1 INCREMENT BY 1 CACHE 50;
CREATE SEQUENCE PM_CHANGE_HISTORY_SEQ START WITH 1 INCREMENT BY 1 CACHE 50;

CREATE TABLE PM_CHANGE_REQUEST (
    ID                 NUMBER(19)       NOT NULL,
    REQUEST_NO         VARCHAR2(40 CHAR) NOT NULL,
    TITLE              VARCHAR2(200 CHAR) NOT NULL,
    DESCRIPTION        VARCHAR2(1000 CHAR),
    STATUS             VARCHAR2(30 CHAR) NOT NULL,
    CREATED_BY         VARCHAR2(100 CHAR) NOT NULL,
    CREATED_BY_NAME    VARCHAR2(200 CHAR) NOT NULL,
    CREATED_AT         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    DECIDED_BY         VARCHAR2(100 CHAR),
    DECIDED_BY_NAME    VARCHAR2(200 CHAR),
    DECIDED_AT         TIMESTAMP(6) WITH TIME ZONE,
    DECISION_NOTE      VARCHAR2(1000 CHAR),
    ROW_VERSION        NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PM_CHANGE_REQUEST PRIMARY KEY (ID),
    CONSTRAINT UK_PM_CHANGE_REQUEST_NO UNIQUE (REQUEST_NO),
    CONSTRAINT CK_PM_CHANGE_REQUEST_STATUS CHECK (
        STATUS IN ('WAITING_APPROVAL', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'FAILED_CONFLICT'))
);

CREATE TABLE PM_CHANGE_ITEM (
    ID                       NUMBER(19) NOT NULL,
    CHANGE_REQUEST_ID        NUMBER(19) NOT NULL,
    RESOURCE_CODE            VARCHAR2(100 CHAR) NOT NULL,
    OPERATION_TYPE           VARCHAR2(20 CHAR) NOT NULL,
    RECORD_ID                VARCHAR2(300 CHAR),
    CLIENT_REFERENCE         VARCHAR2(100 CHAR),
    REFERENCE_BINDINGS_JSON  CLOB,
    OLD_VALUE_JSON           CLOB,
    NEW_VALUE_JSON           CLOB,
    EXPECTED_VERSION         NUMBER(19),
    EXECUTION_ORDER          NUMBER(10) NOT NULL,
    STATUS                   VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT PK_PM_CHANGE_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_PM_CHANGE_ITEM_REQUEST FOREIGN KEY (CHANGE_REQUEST_ID)
        REFERENCES PM_CHANGE_REQUEST (ID),
    CONSTRAINT CK_PM_CHANGE_ITEM_OP CHECK (OPERATION_TYPE IN ('CREATE', 'UPDATE', 'DELETE')),
    CONSTRAINT CK_PM_CHANGE_ITEM_STATUS CHECK (STATUS IN ('PENDING', 'APPLIED')),
    CONSTRAINT CK_PM_CHANGE_ITEM_OLD_JSON CHECK (OLD_VALUE_JSON IS JSON),
    CONSTRAINT CK_PM_CHANGE_ITEM_NEW_JSON CHECK (NEW_VALUE_JSON IS JSON),
    CONSTRAINT CK_PM_CHANGE_ITEM_REF_JSON CHECK (REFERENCE_BINDINGS_JSON IS JSON)
);

CREATE TABLE PM_CHANGE_HISTORY (
    ID                 NUMBER(19) NOT NULL,
    CHANGE_REQUEST_ID  NUMBER(19) NOT NULL,
    ACTION             VARCHAR2(30 CHAR) NOT NULL,
    ACTION_BY          VARCHAR2(100 CHAR) NOT NULL,
    ACTION_BY_NAME     VARCHAR2(200 CHAR) NOT NULL,
    ACTION_AT          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    NOTE               VARCHAR2(1000 CHAR),
    CONSTRAINT PK_PM_CHANGE_HISTORY PRIMARY KEY (ID),
    CONSTRAINT FK_PM_CHANGE_HISTORY_REQUEST FOREIGN KEY (CHANGE_REQUEST_ID)
        REFERENCES PM_CHANGE_REQUEST (ID)
);

CREATE INDEX IX_PM_REQUEST_STATUS_DATE ON PM_CHANGE_REQUEST (STATUS, CREATED_AT);
CREATE INDEX IX_PM_REQUEST_CREATED_BY ON PM_CHANGE_REQUEST (CREATED_BY, CREATED_AT);
CREATE INDEX IX_PM_ITEM_REQUEST ON PM_CHANGE_ITEM (CHANGE_REQUEST_ID, EXECUTION_ORDER);
CREATE INDEX IX_PM_HISTORY_REQUEST ON PM_CHANGE_HISTORY (CHANGE_REQUEST_ID, ACTION_AT);

