CREATE SEQUENCE PRM_LOAN_RATE_SEQ START WITH 1 INCREMENT BY 1 CACHE 20;

CREATE TABLE PRM_LOAN_PRODUCT (
    PRODUCT_CODE   VARCHAR2(30 CHAR) NOT NULL,
    PRODUCT_NAME   VARCHAR2(150 CHAR) NOT NULL,
    CURRENCY_CODE  VARCHAR2(3 CHAR) NOT NULL,
    STATUS         VARCHAR2(20 CHAR) NOT NULL,
    ROW_VERSION    NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PRM_LOAN_PRODUCT PRIMARY KEY (PRODUCT_CODE),
    CONSTRAINT CK_PRM_LOAN_PRODUCT_STATUS CHECK (STATUS IN ('ACTIVE', 'PASSIVE'))
);

CREATE TABLE PRM_LOAN_RATE (
    ID              NUMBER(19) NOT NULL,
    PRODUCT_CODE    VARCHAR2(30 CHAR) NOT NULL,
    TERM_MONTH      NUMBER(3) NOT NULL,
    MIN_AMOUNT      NUMBER(19,2) NOT NULL,
    INTEREST_RATE   NUMBER(9,6) NOT NULL,
    EFFECTIVE_FROM  DATE NOT NULL,
    ROW_VERSION     NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PRM_LOAN_RATE PRIMARY KEY (ID),
    CONSTRAINT FK_PRM_RATE_PRODUCT FOREIGN KEY (PRODUCT_CODE)
        REFERENCES PRM_LOAN_PRODUCT (PRODUCT_CODE),
    CONSTRAINT UK_PRM_RATE UNIQUE (PRODUCT_CODE, TERM_MONTH, EFFECTIVE_FROM),
    CONSTRAINT CK_PRM_RATE_TERM CHECK (TERM_MONTH BETWEEN 1 AND 120),
    CONSTRAINT CK_PRM_RATE_AMOUNT CHECK (MIN_AMOUNT >= 0),
    CONSTRAINT CK_PRM_RATE_VALUE CHECK (INTEREST_RATE > 0)
);

CREATE INDEX IX_PRM_RATE_PRODUCT ON PRM_LOAN_RATE (PRODUCT_CODE);
CREATE INDEX IX_PRM_RATE_EFFECTIVE ON PRM_LOAN_RATE (EFFECTIVE_FROM);

INSERT INTO PRM_LOAN_PRODUCT (PRODUCT_CODE, PRODUCT_NAME, CURRENCY_CODE, STATUS, ROW_VERSION)
VALUES ('TL_SPOT', 'TL Spot Kredi', 'TRY', 'ACTIVE', 0);

INSERT INTO PRM_LOAN_PRODUCT (PRODUCT_CODE, PRODUCT_NAME, CURRENCY_CODE, STATUS, ROW_VERSION)
VALUES ('ROTATIVE', 'Rotatif Kredi', 'TRY', 'ACTIVE', 0);

INSERT INTO PRM_LOAN_RATE
    (ID, PRODUCT_CODE, TERM_MONTH, MIN_AMOUNT, INTEREST_RATE, EFFECTIVE_FROM, ROW_VERSION)
VALUES
    (PRM_LOAN_RATE_SEQ.NEXTVAL, 'TL_SPOT', 12, 10000, 4.250000, DATE '2026-01-01', 0);

